'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BillRecipientPage

    '''<summary>
    '''btnCreateBillRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateBillRecipient As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblBillRecipientDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBillRecipientDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lvBillRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvBillRecipients As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''hiddenBillRecipientID_Modal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenBillRecipientID_Modal As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblConfirmationMessageBillRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmationMessageBillRecipient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnConfirmPaymentModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmPaymentModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hiddenBillID_Modal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenBillID_Modal As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlRecipientUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRecipientUser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTotalUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalUsers As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkSplitEvenly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSplitEvenly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlTaxStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTaxStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTaxCharged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTaxCharged As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCreateBillRecipientModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateBillRecipientModal As Global.System.Web.UI.WebControls.Button
End Class
