'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DashboardPage

    '''<summary>
    '''lblMoneyOwnedTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMoneyOwnedTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lvMoneyOwnedDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvMoneyOwnedDetails As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''lblBillsToBePaidTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBillsToBePaidTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lvBillsToBePaidDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvBillsToBePaidDetails As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''btnAddBill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddBill As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblTotalBillsCreated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalBillsCreated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalBillsPaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalBillsPaid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalBillsPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalBillsPending As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltMessageBill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltMessageBill As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lvBillsCreated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvBillsCreated As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''txtBillAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBillDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBillDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBillDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCreateBill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateBill As Global.System.Web.UI.WebControls.Button
End Class
