'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PaymentHistoryPage

    '''<summary>
    '''lblBillRecipientDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBillRecipientDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lvBillRecipientbyUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvBillRecipientbyUserID As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''hiddenBillRecipientID_Modal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenBillRecipientID_Modal As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblConfirmationMessageBillRecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmationMessageBillRecipient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCreatePaymentModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreatePaymentModal As Global.System.Web.UI.WebControls.Button
End Class
